### PR TITLE
Two bug fixes, lint fixes, and a better median fn

### PR DESCRIPTION
**Pull request by ashenfad**
Bumps to version `4.1.0`.

### CODE REVIEW

**Comment by ashenfad** [comment]
Any comments @jaor?

**Comment by jaor** [comment]
looks good and tests pass.  when compiling the java sources with java
1.7_65 i get the following warnings:

```
Compiling 18 source files to /home/jao/usr/bigml/histogram/target/classes
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
Compiling namespace bigml.histogram.core
```

if you think they're harmless, we can merge and release.

**Comment by ashenfad** [comment]
Okay, the compile should be warning free as of 8bca68b.

**Comment by jaor** [comment]
excellent.  i've merged, pushed and tagged with 4.1.0 the code!

**Pull request merged**
